### ISSUE TITLE
Fail to create custom dataset statistics for KID computation

### ISSUE THREAD

**Issue by BrandoZhang** [GaParmar/clean-fid#10]
Can I create custom dataset statistics to compute KID?

In my trial, after `make_custom_stats`, the invoking of `compute_fid` works fine but `compute_kid` tries to download the statistics:

```bash
>>> fid.compute_kid('sunglasses/0', dataset_name='sunglasses', mode='clean', dataset_res=256, dataset_split='custom')
compute KID of a folder with sunglasses statistics
downloading statistics to /home/brando/.local/lib/python3.7/site-packages/cleanfid/stats/sunglasses_clean_custom_na_kid.npz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brando/.local/lib/python3.7/site-packages/cleanfid/fid.py", line 335, in compute_kid
    mode=mode, seed=0, split=dataset_split, metric="KID")
  File "/home/brando/.local/lib/python3.7/site-packages/cleanfid/features.py", line 95, in get_reference_statistics
    fpath = check_download_url(local_folder=stats_folder, url=url)
  File "/home/brando/.local/lib/python3.7/site-packages/cleanfid/downloads_helper.py", line 27, in check_download_url
    with urllib.request.urlopen(url) as response, open(local_path, 'wb') as f:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Detailed context can be found in https://github.com/GaParmar/clean-fid/issues/9.

**Comment by Hosein47** [comment]
I have the same problem for FID and get the same error.

**Comment by GaParmar** [comment]
For the custom stats error, it looks like your custom dataset statistics file was not created. 
Can you check the files in the folder `os.path.join(os.path.dirname(cleanfid.__file__), "stats")`

**Comment by GaParmar** [comment]
Looking at this lines you do not need these normalization.
[jit detector](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/metrics/metric_utils.py#L270)
If you look at the forward pass function defined within the torchscript inception model, the normalization applied is the same is the one in cleanfid's inceptionv3W class.
